storage:
  # Path to storage directory
  storage_path: ./qdrant_storage

service:
  # Host to bind the service to
  host: 0.0.0.0
  # Port to bind the service to
  http_port: 6333
  # Port to bind the gRPC service to
  grpc_port: 6334

cluster:
  # Enable cluster mode
  enabled: false

telemetry:
  # Disable telemetry
  enabled: false 